name: Test Swift Tools and NTRIP Stream

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-streaming-job:
    runs-on: ubuntu-latest
    env:
      NTRIP_USERNAME: ${{ secrets.NTRIP_USERNAME }}
      NTRIP_PASSWORD: ${{ secrets.NTRIP_PASSWORD }}
      
      # IMPORTANT: Make sure these two values are still correct!
      SWIFT_TOOLS_URL: "https://github.com/shahrzadshariati/Convert-Stream-RTCM-to-JSON/releases/download/v1.0.0-tools/swift-cli-v0.20.0-x86_64-unknown-linux-musl.tar.gz"
      EXPECTED_FILE_SIZE: 44397837 

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Swift Tools
        run: |
          echo "### Downloading and installing Swift Tools... ###"
          curl -L -o swift-tools.tar.gz "${{ env.SWIFT_TOOLS_URL }}"
          
          ACTUAL_SIZE=$(wc -c < swift-tools.tar.gz)
          if [ "$ACTUAL_SIZE" -ne "${{ env.EXPECTED_FILE_SIZE }}" ]; then
            echo "Error: Downloaded file size is incorrect. Expected ${{ env.EXPECTED_FILE_SIZE }}, got $ACTUAL_SIZE."
            exit 1
          fi
          
          mkdir -p $HOME/swift-tools
          tar -xzf swift-tools.tar.gz -C $HOME/swift-tools
          
          echo "$HOME/swift-tools" >> $GITHUB_PATH
          echo "Tools are ready."

      - name: Run a 10-second Test Stream
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "### Starting a 10-second test stream... ###"
          # Add the -vv flag for "very verbose" output
          timeout 10s swift ntripping -vv \
            --username "${{ env.NTRIP_USERNAME }}" \
            --password "${{ env.NTRIP_PASSWORD }}" \
            --url https://eu.l1l2.skylark.swiftnav.com:2102/SSR-integrity \
            --lat 52.149 \
            --lon 13.096 | swift rtcm32json > log.rtcm.json.test
          continue-on-error:true 
          

      - name: Upload Test Log File
        uses: actions/upload-artifact@v4
        with:
          name: ntrip-test-log
          path: log.rtcm.json.test
